name: Build APK

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
 contents: write
 actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre-headless python3 python3-bs4 python3-requests curl jq

      - name: Build and release APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          ./build.sh
